# Final Project - Task 07
# Jordan Reinhardt
# December 13, 2024

---
# Role Tasks
- name: Enable Web Server Ports
  ansible.posix.firewalld:
    service: '{{ item }}'
    permanent: true
    state: enabled
  with_items:
    - http
    - https
  become: true

- name: Restart Firewalld to take in new changes
  ansible.builtin.systemd_service:
    name: firewalld
    state: reloaded
  become: true
