# Final Project - Task 08
# Jordan Reinhardt
# December 13, 2024

---
# Roles Tasks
- name: Update DNF Cache
  ansible.builtin.dnf:
    update_cache: true
  become: true

- name: Install Postfix
  ansible.builtin.dnf:
    name: postfix
    state: latest
  become: true

- name: Push Postfix services
  ansible.builtin.template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    group: root
    owner: root
    mode: '0644'
  become: true

- name: Add Test Users
  ansible.builtin.user:
    name: '{{ item }}'
    shell: /sbin/nologin
    create_home: yes
    password: '{{ item }}'
  with_items:
    - user01
    - user02
    - user03
  become: true

- name: Add user Maildir directory
  ansible.builtin.file:
    path: '/home/{{ item }}/Maildir'
    state: directory
    group: '{{ item }}'
    owner: '{{ item }}'
    mode: '0755'
  with_items:
    - user01
    - user02
    - user03
  become: true

- name: Restart Postfix
  ansible.builtin.service:
    name: postfix
    state: restarted
  become: true

- name: Allow SMTP Inbound
  ansible.builtin.firewalld:
    service: smtp
    permanent: yes
    state: enabled
  become: true

- name: Reload firewall
  ansible.builtin.systemd_service:
    name: firewalld
    state: reloaded
  become: true
